### ISSUE TITLE
Periodic Boundary Conditions

### ISSUE THREAD

**Issue by dveyrat** [DESI-UR/VAST#35]
Modify VoidFinder and Vsquared to be able to properly process inputs with periodic boundary conditions.

**Comment by QuiteAFoxtrot** [comment]
We just merged #70 for VoidFinder - is there anything left for V^2 or is this one ready to be closed?

**Comment by kadglass** [comment]
All documentation has also been updated (in PR #75 ), as well as V^2.  This issue can now be closed.
