### ISSUE TITLE
Update docs for new mask parameter options

### ISSUE THREAD

**Issue by QuiteAFoxtrot** [DESI-UR/VAST#44]
With the updates to enable xyz-style masks added the optional parameter xyx_limits and the switch mask_mode which should be documented for users

**Comment by kadglass** [comment]
ReadTheDocs also needs to be updated to describe both input/mask options (sky coordinates and Cartesian coordinates).

**Comment by kadglass** [comment]
The docs were updated with the new mask options and merged in with PR #75 .
