### ISSUE TITLE
Missing pyopengltk in requirements.txt

### ISSUE THREAD

**Issue by lavaux** [DESI-UR/VAST#51]
It seems that pyopengltk is missing in the list of requirements for VoidFinder. 

https://github.com/openjournals/joss-reviews/issues/4033

**Comment by QuiteAFoxtrot** [comment]
@kadglass @dveyrat @sybenzvi have any of you guys added anything that uses pyopengltk?  The 3D VoidRender stuff uses OpenGL, PyOpenGL, and Vispy, but I have never encountered pyopengltk unless maybe pip pulled the wool over my eyes and something is using it that we don't know about

**Comment by QuiteAFoxtrot** [comment]
Was able to reproduce the issue

**Comment by QuiteAFoxtrot** [comment]
#68
