### ISSUE TITLE
comments on paper

### ISSUE THREAD

**Issue by changhoonhahn** [DESI-UR/VAST#52]
openjournals/joss-reviews#4033

# major comments
- I think the "statement of need" for the paper needs to be sharpened. The speed of void finders is cited as the main problem the software is designed to solve at the moment. However, the paper does not state whether the Python3 implementations of VoidFinder and Vsquared are faster than the previous versions. 
- Also, I think the target audience could be more clearly stated. Is the target audience cosmologists who are interested in constraining cosmological parameters using voids? If so, some citations to void forecasts, for instance, would be helpful. 

# minor comments
- VoidFinder Section: I think some of the details are a bit vague. For instance, it's not clear to me how "the centers of empty cells" are defined or the "remaining holes".
- V2 Section: It would be helpful if a brief summary of one of the void pruning algorithm (VIDE or REVOLVER) is provided. 
- Figure 1 captions: A more detailed description would be very helpful. For example, what is the difference between the black and red points? How are the black points connected?

**Comment by kadglass** [comment]
@dveyrat I have updated the `paper.md` file on the docs branch based on some of these comments.  Could you please add a short description of one of the void pruning methods to the V2 section?

**Comment by sybenzvi** [comment]
@kadglass, your rewrite of the VoidFinder description is good. But I don't recall you profiling the FORTRAN version... I would have remembered 36 hours (!) to run on DR7.

About the ZOBOV packages, the initial motivation to write V2 was that @dveyrat found ZOBOV implementations in the wild to be abandonware or very difficult to run and install. (REVOLVER is an exception.) I wouldn't put that into the statement of need, but the statement could emphasize that V2 consolidates a large number of pruning methods in a single package.

**Comment by kadglass** [comment]
Michaela ran the Fortran code when we first started working on this project - that is how long it took her to run it!  I can see if I can compile and run the Fortran code again to confirm that runtime.

Good idea on V2 - I will add something about that to the statement.
