### ISSUE TITLE
Missing vsquared/__init__.py after the move

### ISSUE THREAD

**Issue by lavaux** [DESI-UR/VAST#62]
Hi,

It seems that __init__.py is missing in python/vast/vsquared which causes the package not to be installed.

**Comment by sybenzvi** [comment]
@lavaux, I'm not reproducing your issue, but it may be due to different installation methods and enviroments. I start from a clean conda environment, run

`pip install -r requirements.txt`

and then

`python setup.py install`.

**Comment by sybenzvi** [comment]
Sorry @lavaux, turns out you were exactly right. I didn't catch it because my source and build trees weren't clean, and there was an __init__.py hanging out in the right place but not committed to the master branch. Thanks for raising the issue, it should be fixed now.
