### ISSUE TITLE
Documentation of community guidelines

### ISSUE THREAD

**Issue by lavaux** [DESI-UR/VAST#73]
I do not think that I have found the community guidelines in the documentation to VAST. Could that be added?

**Comment by sybenzvi** [comment]
@kadglass, here are the JOSS review criteria discussing community guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html#community-guidelines

**Comment by sybenzvi** [comment]
Added community guidelines indicating how to contribute to VAST and where to seek support. See current build of online documentation: https://vast.readthedocs.io/en/latest/contributing.html.
