### ISSUE TITLE
VF not finding closest galaxy in _query_first()

### ISSUE THREAD

**Issue by kadglass** [DESI-UR/VAST#83]
Potentially a Linux vs Mac issue, but when running an older version of VF against a newer version of VF on the same data, the older version was returning a first bounding galaxy (k1g) which was closer to the original hole center than the newer version of VF.  Need to verify that _query_first() is running correctly and also that the GalaxyMap objects are constructed correctly.

**Comment by QuiteAFoxtrot** [comment]
Wrote a unit test to compare against scikit-learn's KDTree implementation to check on random data, so far looks good both implementations returning the same result on tests against random data.  Could be a Mac/Linux issue, could be an issue with Old Code vs. New Code, could be an issue with the GalaxyMap/grid setup causing slight differences in hole center locations perhaps

**Comment by QuiteAFoxtrot** [comment]
DId an apples-to-apples Linux & Mac test controlling for VAST versions and now getting correct results, closing this.
