### ISSUE TITLE
VoidFinder KeyErrors

### ISSUE THREAD

**Issue by hbrincon** [DESI-UR/VAST#96]
Running VAST/example_scripts/Gadget_VoidFinder_periodic.py with an appropriate bounding volume on the 2Gpc Abacus Simulation hugebase halo catalog results in a continuous stream of KeyErrors (see attached image). It’s unclear if the algorithm is continuing to work despite these errors.
<img width="729" alt="KeyErrors" src="https://github.com/DESI-UR/VAST/assets/102341956/cf88f931-896e-496e-8c49-e0854efa1187">

**Comment by QuiteAFoxtrot** [comment]
@hbrincon VoidFinder should not raise any errors in normal execution so you can be sure the algorithm is not continuing to work correctly in this case.

I'll see if I can get the data from Kelly to run with this - but can you provide:

Minimum reproducing code (did you change anything in Gadget_VoidFinder_periodic.py or is it fresh off a git branch?)
Python environment information (pip list, conda list -n myenv, etc)
VAST branch/commit hash you were running with
Operating System you were running with
compiler version used to build VAST

If you need help obtaining this information in your environment Kelly and I can help

**Comment by QuiteAFoxtrot** [comment]
Discovered a number of issues with the Python 'mmap' object which provides the necessary shared memory resource for VoidFinder, opened a corresponding bug report on the CPython github https://github.com/python/cpython/issues/115635

May have found a temporary workaround until CPython can fix

**Comment by QuiteAFoxtrot** [comment]
PR #110
